version: '2'
services:

  client:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
    image: todorus/openkaart-client:production
    ports:
      - "3000:3000"
      - "3001:3001"
    env_file:
      - client.env
    volumes:
      - ../../client/app:/client/app
